// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwnxpemjljnyhdylikek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bnhwZW1qbGpueWhkeWxpa2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzQ3MDgsImV4cCI6MjA2NDMxMDcwOH0.wT6ojW4MCkE4BtOl3NNvKCKeH7RsEb6NdUFGZR6lgfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);